ERROR_EXPANDO(SUCCESS, "Success")
ERROR_EXPANDO(CONNECT, "Connection failed")
ERROR_EXPANDO(NOMATCH, "Usernames do not match")
ERROR_EXPANDO(PACKET, "Packet transfer error")
ERROR_EXPANDO(BADUSERPASS, "Invalid username or password")
ERROR_EXPANDO(SEQUENCE, "Invalid sequence number from server")
ERROR_EXPANDO(FRAMETYPE, "Invalid frame type from server")
ERROR_EXPANDO(PACKETSIZE, "Packet too long")
ERROR_EXPANDO(SERVER, "Server problem; try again later")
ERROR_EXPANDO(UNKNOWN, "Unknown error")
ERROR_EXPANDO(BLOCKED, "You are blocked")
ERROR_EXPANDO(WEIRDPACKET, "Unknown packet received from server")
ERROR_EXPANDO(CALLBACKNUM, "Invalid callback number")
ERROR_EXPANDO(BADUSER, "Invalid username")
ERROR_EXPANDO(NOTFOUND, "Username not found in list")
ERROR_EXPANDO(DISCONNECT, "Server disconnected")
ERROR_EXPANDO(SOCKET, "Unable to create socket")
ERROR_EXPANDO(RESOLV, "Unable to resolve hostname")
ERROR_EXPANDO(VERSION, "Wrong server version")
ERROR_EXPANDO(USERUNAVAILABLE, "User is currently unavailable")
ERROR_EXPANDO(USERINFOUNAVAILABLE, "User information is currently unavailable")
ERROR_EXPANDO(TOOFAST, "You are sending messages too fast; last message was dropped")
ERROR_EXPANDO(ROOMUNAVAILABLE, "Chat room is currently unavailable")
ERROR_EXPANDO(INCOMINGERROR, "Incoming message delivery failure")
ERROR_EXPANDO(USERDISCONNECT, "User disconnected")
ERROR_EXPANDO(INVALIDFORMAT, "Server response was formatted incorrectly")
ERROR_EXPANDO(IDLEFAST, "You have requested idle to be reset too fast")
ERROR_EXPANDO(BADROOM, "Invalid room name")
ERROR_EXPANDO(BADMESSAGE, "Invalid message (too long?)")
ERROR_EXPANDO(MESSAGETRUNCATED, "Message truncated")
ERROR_EXPANDO(BADPROTO, "Invalid protocol")
ERROR_EXPANDO(NOTCONNECTED, "Not connected")
ERROR_EXPANDO(BADCONNECTION, "Invalid connection number")
ERROR_EXPANDO(NOPERMS, "No permission to perform operation")
ERROR_EXPANDO(NOCHANGEPASS, "Unable to change password")
ERROR_EXPANDO(DUPEROOM, "Room already in list")
ERROR_EXPANDO(IOERROR, "Input/output error")
ERROR_EXPANDO(BADHANDLE, "Invalid handle")
ERROR_EXPANDO(TIMEOUT, "Operation timed out")
